wokeserver:
  hosts:
    stay.woke.net:
    get.woke.net:
  vars:
    ansible_ssh_pipelining: yes

anchorbot:
  hosts:
    get.woke.net:
  vars:
    ansible_ssh_pipelining: yes

tinycount:
  hosts:
    get.woke.net:
  vars:
    ansible_ssh_pipelining: yes
