---
- name: Provision woke server
  hosts: intl
  remote_user: ansible
  become: yes
  roles:
    - base
    - gstreamer-nvenc
    - geerlingguy.nodejs
    - streamwall
    - streambackup
    - mrlesmithjr.netdata
 