---
- name: Provision woke server
  hosts: wokeserver
  remote_user: ansible
  become: yes
  roles:
    - base
    - gstreamer-nvenc
    - geerlingguy.nodejs
    - streamwall

- name: Set up anchorbot
  hosts: anchorbot
  remote_user: ansible
  become: yes
  tags: anchorbot
  roles:
    - anchorbot
