user_service_dir: "/home/streamwall/.config/systemd/user"
streamwall_config_path: "/home/streamwall/streamwall.config.toml"
streamwall_active_color: "#800080"
streamdelay_config_path: "/home/streamwall/streamdelay.config.json"
streamdelay_overlay_image_path: "/home/streamwall/stream-content/content/bleep.png"

xorg_conf: xorg.conf.j2
xorg_nvidia_busid: ""
streamwall_cpu_affinity: ""
streamcapture_cpu_affinity: ""
streamcapture_x264_threads: 0
streamdelay_cpu_affinity: ""
streamdelay_x264_threads: 0
streamcapture_encoder: ""

content_git_repo: "{{ vault_content_git_repo | default('https://github.com/streamwall/example-content.git') }}"
stream_rtmp_destinations: "{{ vault_stream_rtmp_destinations }}"
streamwall_announce_api_token: "{{ vault_streamwall_announce_api_token }}"
streamwall_control_user: "{{ vault_streamwall_control_user }}"
streamwall_control_password: "{{ vault_streamwall_control_password }}"
streamdelay_api_key: "{{ vault_streamdelay_api_key }}"
vnc_password: "{{ vault_vnc_password }}"
streamwall_json_location: "{{ vault_streamwall_json_location | default('https://woke.net/api/streams.json') }}"
