---
- name: Add caddy PPA
  apt_repository:
    repo: "deb [trusted=yes] https://apt.fury.io/caddy/ /"
    state: present
  register: caddy_repo

- name: Update apt cache if repo was added
  apt:
    update_cache: yes
  when: caddy_repo.changed

- name: Install caddy
  apt:
    name: caddy
    state: present

- name: Create caddy log dir
  file:
    path: /var/log/caddy
    state: directory
    owner: caddy
    group: caddy

- name: Hash origin password
  shell: caddy hash-password -plaintext {{ cdn_origin_password }}
  register: caddy_hash_result

- set_fact:
    hashed_cdn_origin_password: "{{ caddy_hash_result.stdout }}"

- name: Add Caddyfile
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
  notify:
    - Reload caddy
