---
- name: Install fonts from apt
  apt:
    name:
      - fonts-arphic-ukai
      - fonts-arphic-uming
      - fonts-ipafont-mincho
      - fonts-ipafont-gothic
      - fonts-unfonts-core
    state: present
    update_cache: true
  become: true
