---
- name: Install electron dependencies
  apt:
    name:
      - ca-certificates
      - libappindicator3-1
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libc6
      - libcairo2
      - libcups2
      - libdbus-1-3
      - libexpat1
      - libfontconfig1
      - libgbm1
      - libgcc1
      - libglib2.0-0
      - libgtk-3-0
      - libnspr4
      - libnss3
      - libpango-1.0-0
      - libpangocairo-1.0-0
      - libstdc++6
      - libx11-6
      - libx11-xcb1
      - libxcb1
      - libxcomposite1
      - libxcursor1
      - libxdamage1
      - libxext6
      - libxfixes3
      - libxi6
      - libxrandr2
      - libxrender1
      - libxss1
      - libxtst6
      - lsb-release
      - xdg-utils

- name: Update streamwall repo
  git:
    repo: https://github.com/chromakode/streamwall.git
    dest: /home/streamwall/streamwall
    version: release
    update: yes
    force: yes
  become: yes
  become_user: streamwall
  register: streamwall_repo

- name: Install streamwall npm deps
  npm:
    path: /home/streamwall/streamwall
  become: yes
  become_user: streamwall
  when: streamwall_repo.changed

- name: Write streamwall config
  template:
    src: streamwall.config.toml.j2
    dest: "{{ streamwall_config_path }}"
    owner: streamwall
    group: streamwall

- name: Add streamwall service file
  template:
    src: streamwall.service.j2
    dest: "{{ user_service_dir }}/streamwall.service"
    owner: streamwall
    group: streamwall
  notify:
    - Reload user systemd
    - Enable streamwall
