---
- name: Install streamcapture dependencies
  apt:
    name:
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - gstreamer1.0-tools
      - swh-plugins

- name: Add streamcapture script
  template:
    src: streamcapture.sh.j2
    dest: /home/streamwall/streamcapture.sh
    mode: +x
    owner: streamwall
    group: streamwall

- name: Add streamcapture service file
  template:
    src: streamcapture.service.j2
    dest: "{{ user_service_dir }}/streamcapture.service"
    owner: streamwall
    group: streamwall
  notify:
    - Reload user systemd
    - Enable streamcapture
