---
- name: "[sysctl] Kernel network tuning - net.core.rmem_max..."
  ansible.posix.sysctl:
    name: net.core.rmem_max
    value: '16777216'

- name: "[sysctl] Kernel network tuning - net.core.wmem_max..."
  ansible.posix.sysctl:
    name: net.core.wmem_max
    value: '16777216'

- name: "[sysctl] Kernel network tuning - net.core.rmem_default..."
  ansible.posix.sysctl:
    name: net.core.rmem_default
    value: '16777216'

- name: "[sysctl] Kernel network tuning - net.core.wmem_default..."
  ansible.posix.sysctl:
    name: net.core.wmem_default
    value: '16777216'

- name: "[sysctl] Kernel network tuning - net.core.optmem_max..."
  ansible.posix.sysctl:
    name: net.core.optmem_max
    value: '40960'

- name: "[sysctl] Kernel network tuning - net.ipv4.tcp_rmem..."
  ansible.posix.sysctl:
    name: net.ipv4.tcp_rmem
    value: '4096 1048576 16777216'

- name: "[sysctl] Kernel network tuning - net.ipv4.tcp_wmem..."
  ansible.posix.sysctl:
    name: net.ipv4.tcp_wmem
    value: '4096 65536 16777216'

- name: "[sysctl] Kernel network tuning - net.core.netdev_max_backlog..."
  ansible.posix.sysctl:
    name: net.core.netdev_max_backlog
    value: '100000'

- name: "[sysctl] Kernel network tuning - net.core.netdev_budget..."
  ansible.posix.sysctl:
    name: net.core.netdev_budget
    value: '50000'

- name: "[sysctl] Kernel network tuning - net.ipv4.tcp_max_syn_backlog..."
  ansible.posix.sysctl:
    name: net.ipv4.tcp_max_syn_backlog
    value: '30000'

- name: "[sysctl] Kernel network tuning - net.ipv4.tcp_max_tw_buckets..."
  ansible.posix.sysctl:
    name: net.ipv4.tcp_max_tw_buckets
    value: '2000000'

- name: "[sysctl] Kernel network tuning - net.ipv4.tcp_tw_reuse..."
  ansible.posix.sysctl:
    name: net.ipv4.tcp_tw_reuse
    value: '1'

- name: "[sysctl] Kernel network tuning - net.ipv4.tcp_fin_timeout..."
  ansible.posix.sysctl:
    name: net.ipv4.tcp_fin_timeout
    value: '10'

- name: "[sysctl] Kernel network tuning - net.ipv4.tcp_slow_start_after_idle..."
  ansible.posix.sysctl:
    name: net.ipv4.tcp_slow_start_after_idle
    value: '0'

- name: "[sysctl] Kernel network tuning - net.ipv4.udp_rmem_min..."
  ansible.posix.sysctl:
    name: net.ipv4.udp_rmem_min
    value: '8192'

- name: "[sysctl] Kernel network tuning - net.ipv4.udp_wmem_min..."
  ansible.posix.sysctl:
    name: net.ipv4.udp_wmem_min
    value: '8192'

- name: "[sysctl] Kernel filesystem tuning - fs.file-max..."
  ansible.posix.sysctl:
    name: fs.file-max
    value: '262144'
